#コンテキストパス設定
server.servlet.context-path=/practice

#ポート番号
#Spring Boot（標準で 8080）と、OracleのWeb管理機能（8080）を同じPCで同時に起動すると
#競合が発生してエラーになるため、SpringBoot側で要変更。
server.port=5555

#キャッシュ無効
spring.thymeleaf.cache=false