#コンテキストパス設定
server.servlet.context-path=/practice

#ポート番号
#Spring Boot（標準で 8080）と、OracleのWeb管理機能（8080）を同じPCで同時に起動すると
#競合が発生してエラーになるため、SpringBoot側で要変更。
server.port=5555

#キャッシュ無効
spring.thymeleaf.cache=false

#SQL接続初期設定
#自分のPC（localhost:1521）で動いているOracleデータベース（xepdb1）に対し
#spring_practiceというユーザーでログインしてJavaからSQLを操作できるようにする。
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#21cの場合のURL
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
#データベースユーザー名、パスワード
spring.datasource.username=spring_practice
spring.datasource.password=systemsss
